version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: rrhh_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: backend
      POSTGRES_USER: recursos_humanos
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - rrhh_network

  # Backend Laravel
  backend:
    build:
      context: ./recursos_humanos-backend
      dockerfile: Dockerfile
    container_name: rrhh_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./recursos_humanos-backend:/var/www/html
      - backend_vendor:/var/www/html/vendor
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=backend
      - DB_USERNAME=recursos_humanos
      - DB_PASSWORD=123456
    depends_on:
      - postgres
    networks:
      - rrhh_network
    command: >
      sh -c "php artisan serve --host=0.0.0.0 --port=8000"

  # Frontend React
  frontend:
    build:
      context: ./recursos-humanos-frontend
      dockerfile: Dockerfile
    container_name: rrhh_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./recursos-humanos-frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
      - VITE_APP_VERSION=1.0.0
      - VITE_APP_NAME=Recursos Humanos
      - VITE_APP_DESCRIPTION=Sistema de Gestión de Recursos Humanos
    depends_on:
      - backend
    networks:
      - rrhh_network
    command: >
      sh -c "npm run dev -- --host 0.0.0.0 --port 3000"

volumes:
  postgres_data:
  backend_vendor:
  frontend_node_modules:

networks:
  rrhh_network:
    driver: bridge
